// src/app/shared/ownid/ownid.component.ts
import { ConsoleLogger } from '@services/console-logger.service';
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  Input,
  ElementRef,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'ownid',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OwnidComponent implements OnInit, OnDestroy {
  @Input() type: string | null = null;

  @Input() data: unknown | null = null;
  
  @Input() partial: boolean = false;

  @Output() onLogin = new EventEmitter();

  @Output() onRegister = new EventEmitter();

  @Output() onLink = new EventEmitter();

  @Output() onRecover = new EventEmitter();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private ownidWidget: any;

  constructor(private elRef: ElementRef) {}

  async ngOnInit() {
    // @ts-ignore-next-line
    window.ownid!.init({
      statusInterval: 1000,
      URLPrefix: environment.ownidURLPrefix,
      logger: new ConsoleLogger(),
      logLevel: 'info',
    });

    if (this.type === 'link') {
      // @ts-ignore-next-line
      this.ownidWidget = await window.ownid!.gigya.renderLink(
        {
          element: this.elRef.nativeElement,
          type: this.type,
          onLink: this.onLink.emit.bind(this.onLink),
        },
        environment.gigyaApiKey,
      );
    } else {
      // @ts-ignore-next-line
      this.ownidWidget = window.ownid!.render({
        element: this.elRef.nativeElement,
        type: this.type,
        partial: this.partial,
        data: this.data,
        language: 'en',
        onLogin: this.onLogin.emit.bind(this.onLogin),
        onRegister: this.onRegister.emit.bind(this.onRegister),
        onLink: this.onLink.emit.bind(this.onLink),
        onRecover: this.onRecover.emit.bind(this.onRecover),
      });
    }
  }

  ngOnDestroy() {
    this.ownidWidget?.destroy();
  }
}

// examples/vue/src/components/controls/OwnId.vue
<template>
  <div ref="ownid-container" class="ownid-container" />
</template>

<script>
/* eslint-disable no-unused-vars */

const environment = {
  ownidURLPrefix : process.env.VUE_APP_OWNID_URL_PREFIX,
  gigyaApiKey: process.env.VUE_APP_GIGYA_API_KEY
};

export default {
  props: ['type', 'data'],
  async mounted() {
    var vm = this;

    // @ts-ignore-next-line
    window.ownid.init({
      statusInterval: 1000,
      URLPrefix: environment.ownidURLPrefix
      // logger: new ConsoleLogger(),
      // logLevel: 'info'
    })

    console.log(this.type)
    if (this.type === 'link') {
      // @ts-ignore-next-line
      this.ownidWidget = await window.ownid.gigya.renderLink(
        {
          element: vm.$refs['ownid-container'],
          type: this.type,
          onLink: () => vm.$emit('link'),
        },
        environment.gigyaApiKey
      )
    } else {
      // @ts-ignore-next-line
      this.ownidWidget = window.ownid.render({
        element: vm.$el,
        type: this.type,
        data: this.data,
        onLogin: vm.$emit.bind(vm, 'login'),
        onRegister: vm.$emit.bind(vm, 'register'),
        onLink: vm.$emit.bind(vm,'link'),
        onRecover: vm.$emit.bind(vm, 'recover')
      })
    }
  }
}
</script>

<style scoped>

</style>
