// projects/demo-app/src/app/shared/ownid/ownid.component.ts
import { ConsoleLogger } from '@services/console-logger.service';
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output
} from "@angular/core";
import WidgetComponent from '../../../../../../src/assets/ownid-web-ui-sdk/components/widget.component';
import { environment } from '../../../environments/environment';

@Component({
  selector: "ownid",
  template: "",
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class OwnidComponent implements OnInit, OnDestroy {
  @Input() type: string | null = null;

  @Input() data: unknown | null = null;

  @Input() partial = false;

  @Output() onLogin = new EventEmitter();

  @Output() onRegister = new EventEmitter();

  @Output() onLink = new EventEmitter();

  @Output() onRecover = new EventEmitter();

  private ownidWidget: WidgetComponent | undefined;

  constructor(private elRef: ElementRef) {}

  async ngOnInit() {
    // @ts-ignore-next-line
    window.ownid!.init({
      statusInterval: 1000,
      URLPrefix: environment.ownidURLPrefix,
      logger: new ConsoleLogger(),
      logLevel: 'info',
    });

    if (this.type === 'link') {
      // @ts-ignore-next-line
      this.ownidWidget = await window.ownid!.renderLinkGigya({
        element: this.elRef.nativeElement,
        type: this.type,
        onLink: this.onLink.emit.bind(this.onLink),
      }, environment.gigyaApiKey);
    } else {
      // @ts-ignore-next-line
      this.ownidWidget = window.ownid!.render({
        element: this.elRef.nativeElement,
        type: this.type,
        data: this.data,
        partial: this.partial,
        onLogin: this.onLogin.emit.bind(this.onLogin),
        onRegister: this.onRegister.emit.bind(this.onRegister),
        onLink: this.onLink.emit.bind(this.onLink),
        onRecover: this.onRecover.emit.bind(this.onRecover),
      });
    }
  }

  ngOnDestroy() {
    this.ownidWidget?.destroy();
  }
}

// examples/vue/src/components/controls/OwnId.vue
<template>
  <div ref="ownid-container" class="ownid-container" />
</template>

<script>
/* eslint-disable no-unused-vars */

const environment = {
  ownidURLPrefix : process.env.VUE_APP_OWNID_URL_PREFIX,
  gigyaApiKey: process.env.VUE_APP_GIGYA_API_KEY
};

export default {
  props: ['type', 'data'],
  async mounted() {
    var vm = this;

    // @ts-ignore-next-line
    window.ownid.init({
      statusInterval: 1000,
      URLPrefix: environment.ownidURLPrefix
      // logger: new ConsoleLogger(),
      // logLevel: 'info'
    })

    console.log(this.type)
    if (this.type === 'link') {
      // @ts-ignore-next-line
      this.ownidWidget = await window.ownid.renderLinkGigya(
        {
          element: vm.$refs['ownid-container'],
          type: this.type,
          onLink: () => vm.$emit('link'),
        },
        environment.gigyaApiKey
      )
    } else {
      // @ts-ignore-next-line
      this.ownidWidget = window.ownid.render({
        element: vm.$el,
        type: this.type,
        data: this.data,
        onLogin: vm.$emit.bind(vm, 'login'),
        onRegister: vm.$emit.bind(vm, 'register'),
        onLink: vm.$emit.bind(vm,'link'),
        onRecover: vm.$emit.bind(vm, 'recover')
      })
    }
  }
}
</script>

<style scoped>

</style>
